(() => { 'use strict';
 const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav-links');
 document.documentElement.classList.add('js');
 const close=()=>{toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');};
 toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
 nav.addEventListener('click',e=>{if(e.target.closest('a'))close();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle.getAttribute('aria-expanded')==='true'){close();toggle.focus();}});
 document.addEventListener('click',e=>{if(!e.target.closest('nav'))close();});
 document.addEventListener('focusin',e=>{if(!e.target.closest('nav'))close();});
 window.matchMedia('(max-width:640px)').addEventListener('change',close);
 const filters=document.querySelector('.filters'),cards=[...document.querySelectorAll('[data-category]')];filters.hidden=false;
 filters.addEventListener('click',e=>{const button=e.target.closest('[data-filter]');if(!button)return;filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;cards.forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter;if(!card.hidden)count++;});document.querySelector('#filter-status').textContent=`${count} ${count===1?'project':'projects'} shown.`;});
 document.querySelector('#year').textContent=new Date().getFullYear();
})();
